{{- if .Values.createConfigMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
{{- range $key, $value := .Values.configs }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}